### PR TITLE
Chinese translation

### PR DESCRIPTION
**Pull request by emlys**
Adds the Chinese RST files. Since we did not get translated images, they point to the original English images.

### CODE REVIEW

**Review by dcdenu4 — APPROVED** [review]
Woohoo!!! Thanks @emlys for doing the leg work on this.

**Comment by dcdenu4** [comment]
Hey @emlys , I had one question I just remembered. Were we going to update the Citation and Contributions section in this PR?

**Comment by dcdenu4** [comment]
Hey @Emily, thanks for updating the Chinese UG contributor list. I noticed that on that commit that the dev build of the UG was not uploaded as an archive, so I couldn't see the latest via google cloud storage.... Should it have uploaded though?

I also noticed the citation was left the same, I can't remember if we decided that should wait for a proper translation or not.

Thanks!

**Comment by emlys** [comment]
> the dev build of the UG was not uploaded as an archive

Good catch! Looks like it's failing to upload because the files already exist, and overwriting them requires delete access to the bucket. I'll make a new service account with delete access.

I didn't realize the citation had changed too, but I think we can copy that over without translation.

**Review by dcdenu4 — APPROVED** [review]
Thanks @emlys !

**Pull request merged**
