### PR TITLE
Consolidate text between UG and args spec (part 2 of 3)

### PR DESCRIPTION
**Pull request by emlys**
- Fisheries
- Fisheries HST
- Finfish
- Forest Carbon
- GLOBIO
- Habitat Quality
- HRA
- Hydropower
- NDR
- Pollination

### CODE REVIEW

**Comment by emlys** [comment]
I didn't put as much effort into the fisheries and finfish aquaculture docs until we know if they're getting deprecated soon.

**Comment by emlys** [comment]
Once again having issues with the GHA workflow not running.

**Review by davemfish — APPROVED** [review]

**Comment by davemfish** [comment]
> 
> This PR also
> 
> * adds support for args that can have multiple types
> * updates the tests for the investspec extension

I don't think I noticed this stuff in the diff. But this PR is so old that maybe those changes were already merged in somewhere else? Anyway these changes look good so I approve! I'll leave it to you to merge because I see that part 1 of 3 is not merged yet either and maybe it's best to merge them in sequence?

**Comment by emlys** [comment]
> I don't think I noticed this stuff in the diff. But this PR is so old that maybe those changes were already merged in somewhere else? 

Oops yep! That was merged already. Ideally we'd merge https://github.com/natcap/invest/pull/633 first, then I can update this one to point to the release/3.10 branch of invest, rather than the feature branch.

**Pull request merged**
