### PR TITLE
Update UG for trademark and NatCap branding

### PR DESCRIPTION
**Pull request by phargogh**
Per a request from the comms team, this PR updates the partner logos and slightly updates a few styles and fonts in keeping with NatCap branding in addition to adding the ® in a few places.

There are a few functional things I wanted to point out as an FYI for the whole software team:

1. Sphinx really doesn't do anything intelligent with images like logos, so I added a script to handle uniform scaling and padding.  When we add a partner org, we should run the script on the logo they give us and commit the resulting image.
2. The `_templates` directory now contains jinja overrides for our theme.  Right now it's pretty simple (just adding fonts and related stylesheets) but could be extended as needed for future theme modifications.  The `Makefile` now excludes dirs prefixed with `_`

Anyways, happy to discuss!

Here's a preview of changes:

Screenshot 2023-09-20 at 4 40 28 PM

### CODE REVIEW

**Review by dcdenu4 — APPROVED** [review]
Thanks @phargogh!

**Review by davemfish — COMMENTED** [review]
Thanks, James, this all sounds good. My only feedback is that it feels like I'm getting blasted with "InVEST" in that upper-left corner. Now that we have the logo there, do we still need the "InVEST" title right below it? Or alternatively, maybe the InVEST logo should replace the image of the lake?

Anyway, no big deal either way.

**Comment by dcdenu4** [comment]
@davemfish, I feel the same way and your comment made me chuckle. It's like those flashing ads: invest, InVEST, INVEST!!!

I know it's a pain to work in this framework, but I wouldn't mind seeing the logo in the upper left, removing the "InVEST" home button below, and is it possible to center the "InVEST User Guide" title?

**Comment by davemfish** [comment]
> and is it possible to center the "InVEST User Guide" title?

This title is left-aligned with the body of text below, there's just a lot of space in between now with the logos. But on other pages, like a model chapter, it probably looks good with the left-alignment.

**Comment by phargogh** [comment]
Thanks for the comments @davemfish and @dcdenu4 !

Although the theme is supposed to be able to hide the brand name below the logo through an option in `conf.py`, that wasn't working for me.  This is now controlled with some custom CSS.  I also added some custom CSS to center-align the UG title, and confirmed that this change does not alter the alignment on other pages.  Screenshots below as a demonstration.
Screenshot 2023-09-21 at 2 35 04 PM
Screenshot 2023-09-21 at 2 35 35 PM

**Review by emlys — APPROVED** [review]
Looks good! Thanks @phargogh

**Review by dcdenu4 — APPROVED** [review]
Thanks @phargogh, looks good.

**Comment by davemfish** [comment]
Thanks for accommodating these nitpicky requests; looks great!

**Pull request merged**
