### PR TITLE
Merge changes from main to 3.9

### PR DESCRIPTION
**Pull request by dcdenu4**
Merging changes that have been made from the main branch into the 3.9 branch to get a more complete up to date version of the InVEST 3.9 UG for the 3.9 release.

### CODE REVIEW

**Comment by dcdenu4** [comment]
@phargogh @emlys , There are some conflicts here and I _think_ I could resolve them, but since you two are the authors on the conflicts in question I'd defer to letting you resolve it. Sound okay?

**Comment by phargogh** [comment]
Sounds good @dcdenu4 !

Some light googling isn't turning up a clear way to merge commits but only for individual files, so @emlys would you like to get on a call sometime and we can hash out the changes?

**Comment by phargogh** [comment]
@dcdenu4 @emlys I just merged the latest changes from `main` into `release/3.9` and resolved the conflicts so this should be ready to review now.

**Review by phargogh — APPROVED** [review]
@dcdenu4 I'm also a little perplexed by what the PR says that a new merge will do.  https://github.com/natcap/invest.users-guide/commit/0d9797ce49e1c4c43186cdd1676a71b928e315fa merges master --> release/3.9 in what I think is a correct resolution to the merge conflicts, and I'm a little surprised that github hasn't marked this PR as merged now that that's gone through.

**Comment by emlys** [comment]
Weird! 0d9797c has the changes I made to the mac installation instructions, but they're not showing up in this PR

**Comment by dcdenu4** [comment]
@phargogh I see you've given this the green light and it looks like everything is in order. Just wanted to make sure with @emlys too, since it was a collab.

**Pull request merged**
